### ISSUE TITLE
the access to the dataset

### ISSUE THREAD

**Issue by GimSungwoo** [shahroudy/NTURGB-D#10]
Hello,
Thanks for your favorable work.
I cannot sent request for the access to the dataset on your website provided by you, 
because it shows '500 - Internal server error'.
Could you probably help me to get Action Recognition Dataset--3D skeletons (body joints) which is 5.8 GB ?
I am an undergraduate student in the UK. I would like to use it to do the research..
My email address is x.jin-17@student.lboro.ac.uk

**Comment by jackasser** [comment]
I got '500 - Internal server error' too.

How to get the data?

**Comment by guofuzheng** [comment]
@jackasser 
Hello , have you got the data? I also met the problem '500 Internal server error' .

**Comment by scutzck033** [comment]
I got '500 - Internal server error' too.
Could you probably help me to get Action Recognition Dataset--3D skeletons (body joints) which is 5.8 GB ? I am an phd student in China. I would like to use it to do the research.
My email address is scutzck033@gmail.com.

**Comment by winbaram1000** [comment]
It will work with adding a “0” to your login ID, if it consists only 3 digit (i.e. if id is R234, please use R0234 instead)

**Comment by shahroudy** [comment]
This error happens some of the time and is a technical problem in the hosting server.
Please contact us via email, so that we can follow this up.
The best person to email is the technician of our lab: Chai Ooy Mei (EOMChai@ntu.edu.sg).
Please CC us (amir3@ntu.edu.sg, jliu029@ntu.edu.sg) in your email so that we can follow it up and ensure you will get access as soon as possible.

**Comment by jackasser** [comment]
@shahroudy  thank you!
