### ISSUE TITLE
About requesting for the NTU RGB-D dataset

### ISSUE THREAD

**Issue by Wei2Huang** [shahroudy/NTURGB-D#13]
Dear friend, I can't got the dataset from the given website because  I can't submit the information with the problem '500 - Internal server error'. Can you give the login ID and password to download the dataset? My email is hw2hwei@foxmail.com. And I can send you my information to prove that I will use the dataset for academic research. Thank you very much!

**Comment by shahroudy** [comment]
This error happens some of the time and is a technical problem in the hosting server.
Please contact us via email, so that we can follow this up.
The best person to email is the technician of our lab: Chai Ooy Mei (EOMChai@ntu.edu.sg).
Please CC us (amir3@ntu.edu.sg, jliu029@ntu.edu.sg) in your email so that we can follow it up and ensure you will get access as soon as possible.
