### ISSUE TITLE
About requesting for the NTURGBD dataset

### ISSUE THREAD

**Issue by rachelgardner121** [shahroudy/NTURGB-D#21]
Dear friend, I have submitted the request for the NTU RGB-D dataset online on 1st, February，2019. But I don't receive any email util today(7th,February，2019) . And my Requester ID is A1941. Please let me know if I don't pass the vertification. Maybe the information I filled in the form is not complete enough. I want to  reapply the dataset online, but 
 I can't resubmit the information with the problem '500 - Internal server error'. Can you give the login ID and password to download the dataset? My email is lily121@sjtu.edu.cn.
 And I can send you my information to prove that I will use the dataset for academic research. Thank you very much!

**Comment by shahroudy** [comment]
This error happens some of the time and is a technical problem in the hosting server.
Please contact us via email, so that we can follow this up.
The best person to email is the technician of our lab: Chai Ooy Mei (EOMChai@ntu.edu.sg).
Please CC us (amir3@ntu.edu.sg, jliu029@ntu.edu.sg) in your email so that we can follow it up and ensure you will get access as soon as possible.
