### ISSUE TITLE
queries about nturgb+d_depth_masked data

### ISSUE THREAD

**Issue by bangligit** [shahroudy/NTURGB-D#4]
Hi,
when I imread your masked depth data (e.g. MDepth-00000001.png), it shows as follows:
![show](https://cloud.githubusercontent.com/assets/26460200/23996200/79636342-0a44-11e7-8c32-c075902b9d56.jpg)

Could you tell me why the masked image just show the top left corner？ 
Thanks very much!

**Comment by TheSOMGuy** [comment]
Ok, well this is fairly an old question but i will give an answer.

It's not always the top left corner, it's just the part of the recorded image where the action happens.
Remember, the dataset is aprrox. somewhat over 1TB in size. 
If they only shipped the uncropped depth masked files, it would be a pain to download the set.
But the uncropped versions are also available.

Cheers.

**Comment by vponcelo** [comment]
In fact, I was wondering whether the Masked Depth Masks refers to the body silhouettes. In your image @bangligit , it seems it is simply a threshold applied to the depth image, so that they do not only consider the body silhouette but all the objects that appear in the foreground for that threshold. Anyway, I would appreciate more details about this. 
Thanks.

**Comment by shahroudy** [comment]
As @TheSOMGuy mentioned, the main purpose of providing masked depthmaps were to have a smaller sized version of the original depth maps.
We used the position of the body skeletons to find regions of interest in depthmaps.
We copied the depth values for the regions of interest (from the original depthmaps) and set the other regions' depth to zero.
This helped to achieve a much more efficient frame-wise compression ratios.
Hope this could help to clarify.
