### ISSUE TITLE
how to split the dataset

### ISSUE THREAD

**Issue by guiyuliu** [shahroudy/NTURGB-D#8]
hello, your design of the dataset is very clever 
I appreciate your work very much , here I want to ask 2 questions 
1. did you use three kinects  on different sdk , if so ,how to keep  them work 
Synchronous . if one，does one kinect  SDK  support 3 kinect cameras  simutaneously?
2.how to split the dataset？ if according to the name， I should  access the name of all the files and then I get the split method ?
Almost all the big datasets have their split file , if you can release  it , a lot of people will appreciate it more 

looking forward to your answer ，thank you

**Comment by TheSOMGuy** [comment]
1) It seems possible to connect more than one Kinect to your computer by using different USB Controllers ( all USB 3 if you use Kinect V2 ).  [Link: 2 kinects, 1 pc!](https://social.msdn.microsoft.com/Forums/en-US/aced0045-8bb2-4c23-b2af-7916972788ac/2-kinects-1-pc?forum=kinectsdk)

Couples of months ago i've read something about increasing the bandwidth of the used USB Bus to enable multiple kinects on the same host. This will ( maybe ) work for the Kinect V1 ( never tried it by myself ). But in common this shouldn't work. Because of the structure of the common USB Bus. Most of them share their bandwidth between the different devices which are connected. But the Kinect is something like a Diva. Means, the first Kinect which is connected to the Bus tells the Bus that it is available and that it will use all the available bandwidth ( remember the size of RBG and Depth + the data of the microphone array, and so on. It's huge. ) Every other Kinect you connect to the host ( on the same USB Bus ) will not recognized because there is a Kinect on that Bus which occupies the bandwidth. 

If you wan't to use multiple Kinects on the same host but on different USB Buses this should be possible. If you wan't to sync them you have a lot to do. One option to do this would be a image based synchronization. This means, you have to place a diode in front of each camera. Then you have to connect all (3) diodes to a clock which enables them to blink synchronous. U can then decide to use a frame wise blinking or something like this. After recording your data u have to make them synchronous by shifting the single streams in position such that all blink events are always on the same time steps. 
Using this you will never reach subframe synchronicity, but frame synchronicity.

2) What do you mean with "spilt file"? If you want to split the data set in training and testing samples you have to do it by yourself. There is no split file. But this is at least one of the simplest parts.

**Comment by shahroudy** [comment]
What we have done for the collection of this dataset was to use 3 PCs each connected to one Kinect v2.
We have connected the 3 PCs via a network switch and have synced the recordings using network connections.

The train/test splits of the dataset have been clearly mentioned in the CVPR paper.
We have defined two evaluation scenarios, cross-subject and cross-view.
All you need to take care of are the subject number or camera number.
Please refer to the CVPR paper for more info about the original dataset and to the TPAMI paper for info about the extended "NTU RGB+D 120" dataset.
